print("==================================================")
print("Welcome to BKG custom car dealer ship request form")
print("==================================================")
print("")
#ask the user selection of make and model
print("1-choose your selection of make and model and put the letter as your answer a-camry toyota,b-corol ahybrid and c-highlander toyota ")
makeAndmodel=input("enter your choice of letter: ")
a=input("camryToyota")
b=input("corolahybrid")
c=input("highlander")
print(f"makeAndmodel {a}")
print(f"makeAndmodel {b}")
print(f"makeAndmodel {c}")
# ask the user about apgreading to sunroof
print("2-would you like to upgrade your car to sunroof? yes or no")
roofType=input("enter your answer:")
print(f"2-upgread roof {roofType}")
# ask the user for colour choice
print("3-what is your choice of colour?")
colourType=input("enter your colour selection")
print(f"3-colour type {colourType}")
# ask the user about apgreading the seat
print("4-would you like to apgread your car seat to leather seat? yes or no")
seatType=input("enter your answer:")
print(f"apgread car seat {seatType}")
#ask the user choise of engine type
print("5-what is your choice of engine selection? a-v6,b-v4 and c-electric engine")
engineType=input("enter your letter of choice: ")
a=input("v6")
b=input("v4")
c=input("electric engine")
print(f"engineType {a}")
print(f"engineType {b}")
print(f"engineType {c}")
# ask the user for apgreading the sound system
print("6-would you like to apgread the sound system to extra surround delux? yes or no")
soundSystem=input("enter your answer: ")
print(f"apgread sound system {soundSystem}")
print("thank you for coming!")
#display the summery
print("summery")
print(f"makeAndmodel {a}")
print(f"makeAndmodel {b}")
print(f"makeAndmodel {c}")
print("")
print(f"upgread roof {roofType}")
print("")
print(f"colour type {colourType}")
print("")
print(f"seatType {seatType}")
print("")
print(f"enginType {a}")
print(f"engineType {b}")
print(f"engineType {c}")
print("")
print(f"upgread sound system {soundSystem}")